### ISSUE TITLE
Clarify object meta autofill

### ISSUE THREAD

**Issue by tomborger** [artsmia/GriotWP#2]
Right now the user is given the option to autofill the object "meta" fields when an object is selected. We don't actually want to encourage that, because WP values will take precedence over API values -- in other words, leaving the meta fields blank will result in fresh data being pulled from the API every load, and that's preferable except in rare cases that the API is wrong. 

Allowing the user to autofill a particular field only when an override is needed might make that process clearer.

**Comment by kjell** [comment]
https://github.com/artsmia/griot/commit/ef0a202fa6d7af60c4744964c0c08b108f8b09fd, https://github.com/artsmia/griot/pull/67.

![screen shot 2015-01-20 at 3 08 55 pm](https://cloud.githubusercontent.com/assets/1378/5826178/595c1926-a0b6-11e4-9153-d77b5c1d836d.png)

I think the 'auto-fill metadata' behavior should be "manual only". If we're overriding the API because it's wrong, we'll do it after the fact. Authors probably don't know if they need to auto-fill at the very beginning of the authoring process, so why ask them?

https://github.com/artsmia/GriotWP/commit/bb9427684554356e4c54470385cffb9b1f7e3b5d disables this for now.
